// n33l4m1n
// Project Euler
// September 29th, 2017
// =====================================================
// Even Fibonacci numbers: program02.c
// Each new term in the Fibonacci sequence is
// generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence
// whose values do not exceed four million,
// find the sum of the even-valued terms.
// =====================================================

#include <stdio.h>
#include <stdlib.h>

#define LIMIT 4000000
// unsigned int range (0 - 4 Billion).
unsigned long int fibonacci(int n);

int main(void)
{
  int answer;
  //long int n = 4000000;

  answer = fibonacci(LIMIT);

  printf("%d\n", answer);

  return 0;
}

// Runtime for this function is O(n), linear.
unsigned long int fibonacci(int n)
{
  long int i;
  int *array = NULL;
  long int sum = 0;

  if (n < 2)
    return n;

  // Storing 0 through n in array, need (n+1) elements.
  array = malloc(sizeof(long int) * (n+1));

  // Set initial conditions for Fibonacci.
  array[0] = 0;
  array[1] = 1;

  // Build Fibonacci array through n.
  for (i = 2; i <= n; i++)
  {
    // Builds Fibonacci array by addition previous two elements.
    array[i] = array[i-1] + array[i-2];
    // Add up all even numbers through one array pass.
    if (array[i] % 2 == 0)
    {
      sum = sum + array[i];
    }
  }

  // Good practice to free memory.
  free(array);

  // Answer
  return sum;
}

// Original code:
// Runtime for unsigned int fibonacci() is exponential.
// Exact runtime is O(φn) ≈ O(1.6n). Why?

/*unsigned int fibonacci(int n)
{
  if (n == 0)
   return 0;
  if (n == 1)
   return 1;
  return fibonacci(n-1) + fibonacci(n-2);
}*/
